import { BENEFIT_CRITERIA, COST_CRITERIA, FILTER_QUESTIONS } from "../constants/questions";

const STORAGE_KEY = "roi_evaluations";

export interface FilterState {
  checks: boolean[];
  notes: string[];
}

export interface Evaluation {
  id: string;
  createdAt: number;
  backgroundInfo: string;
  description: string;
  benefitRatings: Record<string, number>;
  costRatings: Record<string, number>;
  benefitScore: number;
  costScore: number;
  quadrantLabel: string;
  quadrantColor: string;
  quadrantDescription: string;
  filterUsed: boolean;
  filterChecks: boolean[];
  filterNotes: string[];
  filterYesCount: number;
}

export function loadEvaluations(): Evaluation[] {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (!raw) return [];
    return JSON.parse(raw) as Evaluation[];
  } catch {
    return [];
  }
}

export function saveEvaluation(evaluation: Evaluation): void {
  const existing = loadEvaluations();
  const updated = [evaluation, ...existing.filter((e) => e.id !== evaluation.id)];
  localStorage.setItem(STORAGE_KEY, JSON.stringify(updated));
}

export function deleteEvaluation(id: string): Evaluation[] {
  const existing = loadEvaluations();
  const updated = existing.filter((e) => e.id !== id);
  localStorage.setItem(STORAGE_KEY, JSON.stringify(updated));
  return updated;
}

export function generateId(): string {
  return Date.now().toString() + Math.random().toString(36).substring(2, 9);
}

export function buildShareText(e: Evaluation): string {
  const date = new Date(e.createdAt).toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  let text = `RETURN ON INTEGRITY: BENEFIT-COST MATRIX\n`;
  text += `${"─".repeat(44)}\n`;
  text += `Date: ${date}\n`;
  if (e.backgroundInfo?.trim()) {
    text += `\nBACKGROUND INFORMATION\n${e.backgroundInfo.trim()}\n`;
  }
  text += `\nAction: ${e.description || "(untitled)"}\n\n`;

  text += `MATRIX RESULT: ${e.quadrantLabel}\n`;
  text += `${e.quadrantDescription}\n\n`;

  text += `Benefit Score: ${e.benefitScore}/10\n`;
  text += `Cost Score:    ${e.costScore}/10\n\n`;

  text += `BENEFIT RATINGS\n`;
  BENEFIT_CRITERIA.forEach((c) => {
    text += `  • ${c.label}: ${e.benefitRatings[c.key]}/10\n`;
  });

  text += `\nCOST RATINGS\n`;
  COST_CRITERIA.forEach((c) => {
    text += `  • ${c.label}: ${e.costRatings[c.key]}/10\n`;
  });

  if (e.filterUsed) {
    text += `\nCONDITIONAL ADOPTION FILTER (${e.filterYesCount}/5)\n`;
    FILTER_QUESTIONS.forEach((q, i) => {
      const ans = e.filterChecks[i] ? "YES" : "NO";
      const note = e.filterNotes[i]?.trim();
      text += `  ${i + 1}. [${ans}] ${q}`;
      if (note) text += `\n       Note: ${note}`;
      text += `\n`;
    });

    let decision = "";
    if (e.filterYesCount >= 4) decision = "Adopt Immediately";
    else if (e.filterYesCount === 3) decision = "Conditional Adoption";
    else decision = "Defer or Reject";
    text += `\nDecision: ${decision}\n`;
  }

  text += `\n${"─".repeat(44)}\n`;
  text += `Generated by Return on Integrity Matrix`;
  return text;
}
